server:
  port: 8090

spring:
  redis:
    host: 192.168.70.209
    password: 123456
    port: 16379
    database: 3
    timeout: 60s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1s
        max-active: -1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easylock
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: mxc.sdk.lock
